Update CI to go green for now (#7817)
* Update CI

This also disables the bug report template lint and webpacker build temporarily since its been failing for awhile and I haven't been able to resolve. Also updates bundler in bundled with in lock file.

* bundle update nokogiri

* Remove pry and pry-byebug

This isn't needed at the moment. Removing will resolve a Ruby 3.2 error.

```
undefined method `=~' for class `Pry::Code' (NameError)
```