Fix a few more issues
By simplifying the setup to not use namespaces but use just renames of
the actual classes, two more issues reproduced.

* Not being able to infer the correct parent class to retrieve records
  from:

  ```
    And I click "Author Articles"                                 # features/step_definitions/index_views_steps.rb:1
      undefined method `find' for nil:NilClass (NoMethodError)
      ./lib/active_admin/resource_controller/data_access.rb:74:in `scoped_collection'
      ./lib/active_admin/resource_controller/data_access.rb:57:in `find_collection'
      ./lib/active_admin/resource_controller/data_access.rb:44:in `collection'
      ./lib/active_admin/resource_controller/streaming.rb:12:in `index'
      ./features/step_definitions/index_views_steps.rb:2:in `/^I click "(.*?)"$/'
      features/renamed_resource.feature:66:in `And I click "Author Articles"'
  ```

  Fixed by passing the correctly renamed class to inherited_resources's
  `belongs_to` helper.

* Parent class was not being properly "translated" before calling the
  polymorphic route helpers:

  ```
    And I click "Author Articles"                                 # features/step_definitions/index_views_steps.rb:1
      undefined method `new_admin_user_article_path' for #<Admin::ArticlesController:0x000055b6ee43c7b8>
      Did you mean?  new_admin_article_path
                     new_admin_user_password_path
                     new_admin_author_article_path
                     new_admin_user_session_path (ActionView::Template::Error)
      ./lib/active_admin/resource_controller/polymorphic_routes.rb:12:in `polymorphic_path'
  ```

Fixed that it by looking at the parent renamed resource to do the
mapping so that the polymorphic helpers generate the correct route.